# Generated by Django 5.2.3 on 2025-06-23 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_priority_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('CRITICAL', 'Kritik')], default='INFO', max_length=10)),
                ('log_type', models.CharField(choices=[('SECURITY', 'Güvenlik'), ('OPERATION', 'İşlem'), ('ERROR', 'Hata'), ('PERFORMANCE', 'Performans')], default='OPERATION', max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Kaydı',
                'verbose_name_plural': 'Log Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
